---
- name: Create a Tenant, App profile, VRF, Bridge Domain, and many EPGs
  hosts: localhost
  gather_facts: false
  vars:
    aci_host: sandboxapicdc.cisco.com
    aci_username: admin
    aci_password: ciscopsdt
    aci_tenant: Wtest-tenant
    aci_ap_name: Wtest-apps
    aci_bd: Wtest-bridge
    aci_vrf: Wtest-vrf
    phys_domain: Wtest-phys_dom
    block_name: 20-50
    aci_aep: Wtest-AEP
    vlan_pool: Wtest-VLAN-Pool
    aci_contract: cali_to_flo
    filter_entry: http
    ether_name: ip_protocol
    lldp_policy: LLDP-Policy
    cdp_policy: cdp-Policy
  #  port-channel: Port-Channel_Policy
    link_level: Link-Level-Policy

  tasks:      
  - name: Create CDP Interface Policy to enable CDP
    aci_interface_policy_cdp:
      name: Ansible_CDP_Interface_Policy
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      admin_state: true
      state: present
      validate_certs: false

  - name: Add a LLDP interface policy
    aci_interface_policy_lldp:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      lldp_policy: "{{ lldp_policy }}"
      description: LLDP Policy Created via Ansible
      state: present
      validate_certs: false

  - name: Add a port channel interface policy
    aci_interface_policy_port_channel:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      port_channel: Port-Channel_Policy
      description: LACP Port Channel Created via Ansible
      min_links: 1
      max_links: 16
      mode: active
      state: present
      validate_certs: false
      
 # - name: Add a Link Level Policy
   # aci_interface_policy_link_level:
     # host: "{{ aci_host }}"
     # username: "{{ aci_username }}"
     # password: "{{ aci_password }}"
     # link_level_policy: "{{ Link_Level }}"  
     # description: Link Level Policy Created via Ansible
     # auto_negotiation: on
     # speed: 100M
     # link_debounce_interval: 100
     # forwarding_error_correction: cl91-rs-fec
     # state: present
     # validate_certs: false    
      
  - name: Create a Virtual Port Channel (VPC) Interface Policy Group
    aci_interface_policy_leaf_policy_group:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      lag_type: node
      policy_group: VPC-Policy-Group
     # link_level_policy: "{{ Link_Level }}"
      cdp_policy: "{{ cdp_policy }}"
      lldp_policy: "{{ lldp_policy }}"
      port_channel_policy: Port-Channel_Policy
      state: present
      validate_certs: false
      
  - name: Add a new leaf_interface_profile
    aci_interface_policy_leaf_profile:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      leaf_interface_profile: ACI_leafintprfname
      description:  leafintprfname description
      state: present
      validate_certs: false
 
  - name: creating a Leaf Profile with description
    aci_switch_policy_leaf_profile:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      leaf_profile: ACI_Leaf-Profile
      description: sw_description
      state: present
      validate_certs: false
  
  - name: adding a switch policy leaf profile selector associated Node Block range (w/ policy group)
    aci_switch_leaf_selector:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      leaf_profile: ACI_Leaf-Profile
      leaf: leaf_selector_name
      leaf_node_blk: node_blk_name
      from: 1011
      to: 1011
      policy_group: VPC-Policy-Group
      state: present
      validate_certs: false
      
  - name: Associate an Interface Access Port Selector to an Interface Policy Leaf Profile with a Policy Group
    aci_access_port_to_interface_policy_leaf_profile:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      leaf_interface_profile: ACI_leafintprofile
      access_port_selector: ACI_accessportselector
      port_blk: ACI_leafportblk
      from_port: 13
      to_port: 16
      policy_group: VPC-Policy-Group
      state: present
      validate_certs: false     
 
  - name: adding a switch policy leaf profile selector associated Node Block range (w/ policy group)
    aci_switch_leaf_selector:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      leaf_profile: ACI_sw_name
      leaf: leaf-1
      leaf_node_blk: node_blk_name
      from: 1011
      to: 1011
      policy_group: VPC-Policy-Group
      state: present
      validate_certs: false     
      
  
 # - name: Associate an access port block (single port) to an interface selector
  #  aci_access_port_block_to_access_port:
   #   host: "{{ aci_host }}"
    #  username: "{{ aci_username }}"
     # password: "{{ aci_password }}"
    #  interface_profile: ACI_leafintprf
    #  access_port_selector: ACI_accessportselector
    #  port_blk: leafportblkname
    #  from_port: 13
    #  to_port: 13
    #  state: present
    #  validate_certs: false
      
#  - name: Associate an access sub port block (single port) to an interface selector
 #   aci_access_sub_port_block_to_access_port:
  #    host: "{{ aci_host }}"
  #    username: "{{ aci_username }}"
  #    password: "{{ aci_password }}"
  #    leaf_interface_profile: leafintprfname
  #    access_port_selector: accessportselectorname
  #    leaf_port_blk: leafportblkname
  #    from_port: 13
  #    to_port: 13
  #    from_sub_port: 1
  #    to_sub_port: 1
  #    state: present
  #    validate_certs: false
      

      
      
      
