---
- name: Create a Tenant, App profile, VRF, Bridge Domain, and many EPGs
  hosts: localhost
  gather_facts: false
  vars:
    aci_host: sandboxapicdc.cisco.com
    aci_username: admin
    aci_password: ciscopsdt
    aci_tenant: Wtest-tenant
    aci_ap_name: Wtest-apps
    aci_bd: Wtest-bridge
    aci_vrf: Wtest-vrf
    phys_domain: Wtest-phys_dom
    block_name: 20-50
    aci_aep: Wtest-AEP
    vlan_pool: Wtest-VLAN-Pool
    aci_contract: cali_to_flo
    filter_entry: http
    ether_name: ip_protocol

  tasks:      
  - name: Create CDP Interface Policy to enable CDP
    aci_interface_policy_cdp:
      name: Ansible_CDP_Interface_Policy
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      admin_state: true
      state: present
      validate_certs: false

  - name: Add a LLDP interface policy
    aci_interface_policy_lldp:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      lldp_policy: ALLOUSA LLDP Policy Created via Ansible
      description: LLDP Policy Created via Ansible
      state: present
      validate_certs: false

  - name: Add a port channel interface policy
    aci_interface_policy_port_channel:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      port_channel: LACP_Port-Channel
      description: LACP Port Channel Created via Ansible
      min_links: 1
      max_links: 16
      mode: active
      state: present
      validate_certs: false
