---
- name: Create a Tenant, App profile, VRF, Bridge Domain, and many EPGs
  hosts: localhost
  gather_facts: false
  vars:
    aci_host: sandboxapicdc.cisco.com
    aci_username: admin
    aci_password: ciscopsdt
    aci_tenant: Wtest-tenant
    aci_ap_name: Wtest-apps
    aci_bd: Wtest-bridge
    aci_vrf: Wtest-vrf
    phys_domain: Wtest-phys_dom
    aci_aep: Wtest-AEP
    aci_epgs:
      - _epg: FirstState
        _desc: First state EPG
      - _epg: Ayrizona
        _desc: really hot
      - _epg: Utah
        _desc: boring
      - _epg: Nevada
        _desc: hot and expensive
      - _epg: Oklahoma
        _desc: wind whips
      - _epg: Nebraska
        _desc: corn right...corn
      - _epg: Idaho
        _desc: waffle fries
      - _epg: Washington
        _desc: rain I think
      - _epg: California
        _desc: beautiful to visit
      - _epg: Florida
        _desc: watch out for Florida man
      - _epg: LastState
        _desc: Last state EPG
    

  tasks:
  - name: Create a tenant
    aci_tenant:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      tenant: "{{ aci_tenant }}"
      description: Greg Ansible Testing
      state: present
      validate_certs: false

  - name: Add a new AP
    aci_ap:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      tenant: "{{ aci_tenant }}"
      ap: "{{ aci_ap_name }}"
      description: Greg Ansible Testing
      state: present
      validate_certs: false

  - name: Add a new VRF to a tenant
    aci_vrf:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      vrf: "{{ aci_vrf }}"
      tenant: "{{ aci_tenant }}"
      descr: Greg Ansible Testing
      policy_control_preference: enforced
      policy_control_direction: ingress
      state: present
      validate_certs: false

  - name: Add Bridge Domain
    aci_bd:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      tenant: "{{ aci_tenant }}"
      bd: "{{ aci_bd }}"
      vrf: "{{ aci_vrf }}"
      state: present
      validate_certs: false
  
  - name: Add a new VLAN Pool
    aci_vlan_pool:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      pool: Wtest-VLAN-Pool
      pool_allocation_mode: dynamic
      description: Production VLANs
      state: present
      validate_certs: false
      
  - name: Add a new VLAN encap block
    aci_vlan_pool_encap_block:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      pool: Wtest-VLAN-Pool
      block_name: Wtest-VLAN-Block
      block_start: 20
      block_end: 50
      pool_mode: static
      state: present
      validate_certs: false
      
  - name: Add a new physical domain
    aci_domain:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      domain: "{{ phys_domain }}"
      domain_type: phys
      state: present
      validate_certs: false
      
  - name: Add a new AEP
    aci_aep:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      aep: "{{ aci_aep }}"
      description: default
      infra_vlan: true
      state: present    
      validate_certs: false
      
  - name: Add AEP to domain binding
    aci_aep_to_domain: &binding_present
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      aep: "{{ aci_aep }}"
      domain: "{{ phys_domain }}"
      domain_type: phys
      state: present
      validate_certs: false

  - name: Add new EPGs
    aci_epg:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      tenant: "{{ aci_tenant }}"
      ap: "{{ aci_ap_name }}"
      epg: "{{ all_epgs._epg }}"
      description: "{{ all_epgs._desc}}"
      bd: "{{ aci_bd }}"
      priority: unspecified
      intra_epg_isolation: unenforced
      state: present
      validate_certs: false
    loop: "{{ aci_epgs }}"
    loop_control:
      loop_var: all_epgs
      
  - name: Add a new physical domain to EPG binding
    aci_epg_to_domain:
      host: "{{ aci_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      tenant: "{{ aci_tenant }}"
      ap: "{{ aci_ap_name }}"
      epg: "{{ all2_epgs._epg }}"
      domain: "{{ phys_domain }}"
      domain_type: phys
      state: present
      validate_certs: false
    loop: "{{ aci_epgs }}"
    loop_control:
      loop_var: all2_epgs

